plugin:
  bootstrap_package:
    settings:
      cssSourceMapping: true
    view:
      layoutRootPath: 'EXT:tsvwartenberg/Resources/Private/Layouts/'
      partialRootPath: 'EXT:tsvwartenberg/Resources/Private/Partials/'
      templateRootPath: 'EXT:tsvwartenberg/Resources/Private/Templates/'
  bootstrap_package_contentelements:
    view:
      layoutRootPath: 'EXT:tsvwartenberg/Resources/Private/Layouts/ContentElements/'
      partialRootPath: 'EXT:tsvwartenberg/Resources/Private/Partials/ContentElements/'
      templateRootPath: 'EXT:tsvwartenberg/Resources/Private/Templates/ContentElements/'
page:
  logo:
    file: 'EXT:tsvwartenberg/Resources/Public/Images/logo.png'
    fileInverted: 'EXT:tsvwartenberg/Resources/Public/Images/logo.png'
    alt: 'TSV Wartenberg'
    linktitle: 'TSV Wartenberg'
    width: 92
  favicon:
    file: 'EXT:tsvwartenberg/Resources/Public/Icons/favicon.ico'
  fluidtemplate:
    layoutRootPath: 'EXT:tsvwartenberg/Resources/Private/Layouts/Page/'
    partialRootPath: 'EXT:tsvwartenberg/Resources/Private/Partials/Page/'
    templateRootPath: 'EXT:tsvwartenberg/Resources/Private/Templates/Page/'
  theme:
    footernavigation:
      levels: 1
      icon:
        enable: false
      enable: false
    language:
      enable: false
    copyright:
      enable: false
    meta:
      navigationValue: '658,655'